#!/usr/bin/python
# Arch news viewer

import feedparser
import html2text
import os
import sys
import argparse
from sys import stderr
from termcolor import colored
from pprint import pprint


def main():
    parser = argparse.ArgumentParser(
            description='View Arch news'
            )
    parser.add_argument('-n', '--number', default=10, help='Number of articles to show (default 10)')
    args = parser.parse_args()
    n = int(args.number)
    feed = feedparser.parse('https://www.archlinux.org/feeds/news/')
    if len(feed['entries']) < n:
        n = len(feed['entries'])
    for x in range(0,n):
        print(f"[{colored(x,'yellow')}] {feed['entries'][x]['title']}")
    prompt = f'Select 0..{n}, q/x, Enter: '
    key=input(colored(prompt,'green'))
    if key == 'x' or key == 'q':
        sys.exit('Quitting...')
    if key == '':
        sys.exit()
    if key.isnumeric():
        print(f"{colored('---','blue')} [ {colored(feed['entries'][int(key)]['link'],'red')} ]")
        h=html2text.HTML2Text()
        print(h.handle(feed['entries'][int(key)]['summary']))
        h.close()
        print(f"{colored('---','blue')}")
        main()
    sys.exit(f"Invalid key \"{colored(key,'red')}\"")

main()
