#!/bin/sh
if [ $# -ne 1 ]; then
    echo "Need 1 argument (brighter dimmer)"
    exit 1;
fi
getnewbrightness () {
    CURBRIGHT=`light -G | cut -d\. -f 1`
}
# requires user with write access to the
# /sys/class/backlight/*/brightness file
# On arch, this is achieved by adding the user to the 'video' group
if [ $1 = 'brighter' ]; then
    MSG='Brighten'
    light -A 5
elif [ $1 = 'dimmer' ]; then
    MSG='Dim'
    light -U 5
fi
getnewbrightness
echo $MSG $CURBRIGHT
notify-send -a brightchange "$MSG ($CURBRIGHT%)" -i /usr/share/icons/Adwaita/32x32/status/display-brightness-symbolic.symbolic.png

